### ISSUE TITLE
State sync not working without having state sync snapshotting enabled

### ISSUE THREAD

**Issue by Galadrin** [okp4/okp4d#246]
Syncing a node with state sync does not currently work, unless you have snapshotting enabled.
The error looks like this:

```6:46AM INF VerifyHeader hash=8C8D8EC451F01A4F7CF5876BE223FDC854E79EA2A5FC51ABE1857D66B9C2DA9A height=290002 module=light
6:46AM INF Offering snapshot to ABCI app format=2 hash="1Ek�2\a�\n\x19�ٴ��r\x12р\x14�\x03:Ü+�N��\x17�~" height=290000 module=statesync
6:46AM ERR snapshot manager not configured
6:46AM ERR State sync failed err="state sync aborted" module=statesync
```

refer to https://github.com/cosmos/cosmos-sdk/issues/13766

**Comment by bdeneux** [comment]
Thank for reporting this issue, a fix has been made on [v0.46.7](https://github.com/cosmos/cosmos-sdk/blob/release/v0.46.x/CHANGELOG.md#bug-fixes-1) but a temporary workaround ([found in issue](https://github.com/cosmos/cosmos-sdk/issues/13766#issuecomment-1328706696)) could be use until [we upgrade](https://github.com/okp4/okp4d/pull/239) cosmos-sdk. 

`sed -E -i -s  's/snapshot-interval = 0/snapshot-interval = 10000/' $HOME/.okp4d/config/app.toml`
