### ISSUE TITLE
🧠 Logic: 🪪 did_components predicate

### ISSUE THREAD

**Issue by ccamel** [okp4/okp4d#276]
## Purpose

In the `logic` module, provide a predicate that breaks a `DID` into its basic components according to the [w3c DID](https://w3c.github.io/did-core) specification.

## Expected behavior

`did_components/2` is a predicate that breaks a [w3c DID](https://w3c.github.io/did-core) into 5 components: method, id, path, query and fragment. The signature is as follow:

```prolog
did_components(+DID, -Components) is det
did_components(-DID, +Components) is det
```

Where:
  - `DID` represents the DID URI as documented in [w3c DID](https://w3c.github.io/did-core) specification.
  - `Components` is a term `did(Method, ID, Path, Query, Fragment)` following the [DID syntax](https://w3c.github.io/did-core/#did-syntax).  Components that are not found (`null`) are left uninstantiated (variable).

## Example

```sh
okp4d query logic ask "did_components('did:example:123456?versionId=1', C)."
```

## Acceptance Criteria

- The predicate is implemented according to the described behavior and examples
- The predicate passes all test cases
- Any related documentation is updated

**Comment by bdeneux** [comment]
@ccamel I think we can close this one since it was merged (#277) ?
