### ISSUE TITLE
🧠 Logic: 🔑 `sha_hash/2` predicate

### ISSUE THREAD

**Issue by bdeneux** [okp4/okp4d#291]
## 📝 Purpose

In the `logic` module, provide a predicate that return a SHA-256 hash of the given data. 

## 🧪 Expected behavior

`sha_hash/2` is a predicate that return the hash of the given Data. The signature is as follow:

```prolog
sha_hash(+Data, -Hash) is det
sha_hash(+Data, +Hash) is det
```

Where:
  - `Data` represents the data to be hashed with the SHA-256 algorithm.
  - `Hash` is the variable that will contain Hashed value of Data.

Due to the hash algorithm principles, this predicated can be used only in one way. `sha_hash(+Data, -Hash)` and not `sha_hash(-Data, +Hash)`. 

## 🎯 Example

```sh
okp4d query logic ask "sha_hash('foo', Hash)."
```
Will return one solution for the Hash variable completed with the given data (`foo`) hashed. 

## ✅ Acceptance Criteria

- [ ] The predicate is implemented according to the described behavior and examples
- [ ] The predicate passes all test cases
- [ ] Any related documentation is updated

## 🔗 Related predicates

- `hex_bytes/2` : #292

**Comment by ccamel** [comment]
Great!

I would tend to want to rename the predicate `crypto_hash/2` to `sha_hash/2`, if we want to target the [SHA hash ](https://en.wikipedia.org/wiki/Secure_Hash_Algorithms)algorithm family.

Moreover, you can add the following signature for the predicate:

```
crypto_hash(+Data, +Hash) is det
```

**Comment by bdeneux** [comment]
Nice ! I have thinking about adding an `+Option` to the predicate allowing choose algorithm used to hash (SHA-1, SHA-256, SHA-512, ...) but, since I only use the cosmos / tendermint library utilities to the crypto used in the blockchain, only the SHA-256 algorithm is used. 

I'm ok to rename it `sha_hash`, I will update this issue description.
 
To complete your suggestion, `crypto_hash(+Data, +Hash) is det`, I suppose that it's return true if the `Hash` is good with the given `Data` ?
