### ISSUE TITLE
🧠 Logic: 🔑 `hex_bytes/2` predicate

### ISSUE THREAD

**Issue by bdeneux** [okp4/okp4d#292]
## 📝 Purpose

In the `logic` module, bytes can be represented as lists of integers between 0 and 255. Such lists can be converted to and from hexadecimal notation with the following bidirectional relation.

## 🧪 Expected behavior

`hex_bytes/2` is a predicate that convert hex represented bytes to bytes and bytes to hexadecimal encoded string. The signature is as follow:

```prolog
hex_bytes(?Hex, ?List) is det
```

Where:
  - `Hex` is an Atom, string or list of characters in hexadecimal encoding.
  - `List` is the list of integers between 0 and 255 that represent the sequence as lost of bytes.

In addition, when passing hex end list, this predicate return true if the conversion match. 

## 🎯 Example

```sh
okp4d query logic ask "hex_bytes('2c26b46b68ffc68ff99b453c1d30413413422d706483bfa0f98a5e886266e7ae', Bt)."
```

## ✅ Acceptance Criteria

- [ ] The predicate is implemented according to the described behavior and examples
- [ ] The predicate passes all test cases
- [ ] Any related documentation is updated

## 🔗 Related predicates

- `crypto_hash/2` : #291

**Comment by ccamel** [comment]
Great. To fully specify the predicate, I think we can add the following signature:

```
hex_bytes(+Hex, +List) is det
```

This will indicate that the Hex and List arguments can be both provided, and the predicate will return true if the Hex argument corresponds to the byte sequence specified by the List argument.
