### ISSUE TITLE
🧠 Logic: 🗂️ source_file/1 predicate

### ISSUE THREAD

**Issue by amimart** [okp4/okp4d#308]
## 📝 Purpose

In the `logic` module, based on the interpreter's filesystem, provide a predicate to indicate if a file is currently loaded (e.g. through a `consult/1`).

## 🧪 Expected behavior

The `source_file/1` predicate unify the given term with the a loaded source file. The signature is as follows:

```prolog
source_file(?File).
```

Where:
  - `File` represents a loaded source file.

## 🎯 Example

```prolog
?- consult('foo.pl').
true.
?- consult('cosmwasm:cw-storage:okp415ekvz3qdter33mdnk98v8whv5qdr53yusksnfgc08xd26fpdn3ts8gddht?query=%7B%22object_data%22%3A%7B%22id%22%3A%20%224cbe36399aabfcc7158ee7a66cbfffa525bb0ceab33d1ff2cff08759fe0a9b05%22%7D%7D').
true.

?- source_file(File).
File = 'foo.pl'.
File = 'cosmwasm:cw-storage:okp415ekvz3qdter33mdnk98v8whv5qdr53yusksnfgc08xd26fpdn3ts8gddht?query=%7B%22object_data%22%3A%7B%22id%22%3A%20%224cbe36399aabfcc7158ee7a66cbfffa525bb0ceab33d1ff2cff08759fe0a9b05%22%7D%7D'.
```

## ✅ Acceptance Criteria

- [ ] The predicate is implemented according to the described behavior and examples
- [ ] The predicate passes all test cases
- [ ] Any related documentation is updated

__EDIT: Content edited based on @ccamel [comment](https://github.com/okp4/okp4d/issues/308#issuecomment-1470183071)__

**Comment by ccamel** [comment]
Let me check... 🤓
