### ISSUE TITLE
🧠 Add whitelist/blacklist to control filenames in the logic module Virtual File System

### ISSUE THREAD

**Issue by ccamel** [okp4/okp4d#342]
## Idea

The `logic` module enables Prolog predicates (e.g. `consult/1`) to access external resources using a virtual file system. The current implementation only supports the `cosmwasm` scheme, which allows resources to be loaded from a smart contract, but in the future, we may have to support other schemes.

That's why there is a need to regulate the files that can be loaded by the Prolog interpreter of the `logic` module. To address this issue, we suggest implementing a whitelist/blacklist system to manage the authorized filenames that can be accessed during the interpretation of predicates. By utilizing a whitelist, only specified filenames can be used, while a blacklist can prevent the use of specific filenames. This system would provide an additional layer of security, preventing the usage of potentially _harmful_ files.

## Todo

- [ ] specify protos to support whitelist/blacklist expressions
- [ ] implement
- [ ] test

**Comment by amimart** [comment]
Addressed by https://github.com/okp4/okp4d/pull/343
