### ISSUE TITLE
🧠 Logic: 🧱 `json_prolog`, add predicate to convert json to prolog terms

### ISSUE THREAD

**Issue by bdeneux** [okp4/okp4d#348]
## 📝 Purpose

In the `logic` module, we will need a set of new predicates to handle json conversion between json string to prolog term and vice versa. 

## 🧪 Expected behavior

```prolog
json_prolog(?Json, ?Term).
```

Where
- `Json` is the string representation of the json
- `Term` is an Atom that would be unified by the JSON representation as Prolog terms. 

In addition, when passing Json and Term, this predicate return true if both result match.

The canonical representation for Term is:

<table>
<thead>
  <tr>
    <th>Json</th>
    <th>Prolog</th>
    <th>Value</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td>Object</td>
    <td>

Mapped to a term `json(Attributes)`, where `Attributes` is a list of all JSON attributes mapped to a pair term `-(Attribute, Value)`, where `Attribute` is an atom created from the JSON string and `Value` is the JSON value. 

</td>
    <td>

```json
{
  "foo": "bar",
  "foobar": "barfoo"
}
```
Result: 
```prolog
json[-(foo, 'bar'), -(foobar, 'barfoo')]
```

</td>
  </tr>
  <tr>
    <td>Array</td>
    <td>List of JSON values</td>
    <td>

```json
["foo", "bar"]
```
Result:
```prolog
['foo', 'bar']
```

</td>
  </tr>
  <tr>
    <td>String</td>
    <td>Atom</td>
    <td>

```json
"foo"
```
Result:
```prolog
'foo'
```

</td>
  </tr>
  <tr>
    <td>Number</td>
    <td>Number</td>
    <td>

```json
1
```
Result:
```prolog
1
```

</td>
  </tr>
<tr>
    <td>

Constant `true` and `false`

</td>
    <td>

Atom `@(true)` and `@(false)`

</td>
    <td>

```json
true
```
Result:
```prolog
@true
```

</td>
  </tr>
<tr>
    <td>

Constant `null`

</td>
    <td>

Atom `@(null)`

</td>
    <td>

```json
null
```
Result:
```prolog
@null
```

</td>
  </tr>
</tbody>
</table>

**Note:** converting a simple string, boolean, integer or null value are valid json and will be unified to an simple atom.

To ensure determinism on the chain, the result of the JSON conversion is canonicalized by sorting the JSON name attribute. Same behavior for the json representation on prolog : `{"b": "a", "a":"c"}` => `json([a-c,b-a])` and `json([b-a,a-c])` => `{"a":"c", "b":"a"}`.

## 🎯 Example 

Given the following JSON
```json
{
  "s": "string",
  "n": 1,
  "a": ["string1", "string2"],
  "o": {
    "b": true,
    "n": null
  }
}
```

```prolog
json([
  -(s, 'string'),
  -(n, 1),
  -(a, ['string1', 'string2']),
  -(o, json([
    -(b, @true),
    -(n, @null),
  ])
])
```

## ✅ Acceptance Criteria

- [x] The predicate is implemented according to the described behavior and examples
- [x] The predicate passes all test cases
- [x] Any related documentation is updated

## 🔗 References and linked predicate

- SWI-Prolog : https://www.swi-prolog.org/pldoc/man?section=json
- A compatible JSON predicate for Tau Prolog's library's implemented on ichiban/prolog : https://github.com/guregu/predicates/blob/master/taujson/json.go

**Comment by amimart** [comment]
This is excellent! Thanks @bdeneux 🥇 

I think this is functionally speaking complete and pretty suited.

We may just need to mention the edge case of a simple string being a valid JSON.

**Comment by ccamel** [comment]
That's brilliant @bdeneux 🤩!

**Comment by bdeneux** [comment]
Specification updated since implementation of the json empty array fix : https://github.com/okp4/okp4d/issues/398.
