### ISSUE TITLE
🧠 Logic: 🔗 string encoding of URI components `uri_encoded/3`

### ISSUE THREAD

**Issue by bdeneux** [okp4/okp4d#352]
## 📝 Purpose

Implement a prolog predicate to handle URI encoding for string value. Allowing convert string to URI encoded components and decode URI encoded components into string. Also check if a string is correctly encoded. 

## 🧪 Expected behavior

```prolog
uri_encoded(+Component, ?Decoded, ?Encoded) is det
```

Where 
- `Decoded`: represent the string value not encoded
- `Encoded`:  is the URI encoded for `Decoded` 
- `Component`: specifies the URI component where the `Decoded` value is used. It is one of `query`, `fragment`, `path` or `segment`. According to [RFC3986](https://datatracker.ietf.org/doc/html/rfc3986#section-2.1), each component doesn't contains the same characters escaping. Allowed values are : 

  - `query`
  - `fragment` 
  - `path` 
  - `segment` 

**EDITED**: Following @ccamel comment : https://github.com/okp4/okp4d/issues/352#issuecomment-1532647508

## 🎯 Example 

```prolog
uri_encoded(query, 'string to encode', Encoded)
```
`Encoded` will be unified to : `string%20to%20encode`

```prolog
uri_encoded(query, Decoded, 'string%20to%20decode')
```
`Decoded` will be unified to : `string to decode`

```prolog
uri_encoded(query, 'string to decode', 'string%20to%20decode')
```
Should be successful since encoded and decoded strings match each other.

```prolog
uri_encoded(query, 'string to encode', 'string%20to%20decode')
```
Should failed since encoded and decoded string doesn't match.

## ✅ Acceptance Criteria

- [ ] The predicate is implemented according to the described behavior and examples
- [ ] The predicate passes all test cases
- [ ] Any related documentation is updated

## 🔗 References and linked predicate

- SWI-Prolog : https://www.swi-prolog.org/pldoc/doc/_SWI_/library/uri.pl

**Comment by ccamel** [comment]
Is it the same than [uri_encoded/3](https://www.swi-prolog.org/pldoc/doc_for?object=uri%3Auri_encoded/3)?

**Comment by bdeneux** [comment]
@ccamel Yes, exactly, I've changed naming because this one could be used bidirectionally ;). Then I've moved `Component` at the end because I'm wondering if we cannot create another predicate `uri_encoding/2 with the `query` component by default ?

**Comment by ccamel** [comment]
ok I see. I think in that case using the suffix `ed` would be more appropriate as it conveys the idea of the relationship (the state of being encoded) that binds two values together and holds if the predicate is true. And it's compatible with your wish to have a bidirectionnal binding.

Moving the `Component` argument to the end is difficult to decide from my point of view; it's something that can be discussed. I would tend not go to too far from the original signature provided by Swi-Prolog, which is a de facto standard, I guess. And I don't think that prevents introducing other predicates with default arguments, even if they are not positioned first.
