### ISSUE TITLE
🧠 Logic: 🗂️ on virtual file URI : allow query non base64 encoded wasm contract response

### ISSUE THREAD

**Issue by bdeneux** [okp4/okp4d#384]
## 📝 Description

#305 introduce the virtual file system allowing us to query smart contract through an URI and consult result into prolog. It was designed that the result of the smart contract query assume is an objectarium smart contract, in consequence, objectarium query response is a JSON containing base64 encoded data. When we call any `cosmwasm:` URI, the response is always converted to json and decoded to data from base64. 

```
cosmwasm:{contract_name}:{contract_address}?query={contract_query}.
```

## 💡 Proposed solution

We could add a new query parameter called `options` allowing pass a set of options to the virtual file system to handle the query. For this particular case, I suggest to add an option : `decode_base64` that indicate the result is base64 encoded and we need to decode it before send the data to the requester.  

```
cosmwasm:{contract_name}:{contract_address}?query={contract_query}[&options=[decode_base64]].
```

## 🤯 Breaking change

Considering this option is not by default, current deployed prolog that use the `consult/1` predicate and call an objectarium contract will no longer working if we didn't indicate the `decode_base64` option. A solution would be to override the `consult/1` predicate implemented by `ichiban/prolog` library and use our own `consult/1` by adding automatically the `decode_base64` option if it's an objectarium contract, we could indicate as deprecated until we update all our references in tutorials, nemeton program, documentations, ... and remove this hack on future release. 

## 🔗 Related link and predicate
- #379 `open/4` use virtual file system and need to query wasm contract without the base64 decoding.

## Let's discuss on it ;)

**Comment by bdeneux** [comment]
Another solution to avoid breaking change is to reimplement the `consult/1` predicate by decoding always the result of the virtual file system. And remove the base64 decoding from the wasm handler of the virtual file system and move it to the custom consult implementation. No need to implement the `options` query on URI.

With that, we consider that all consult require base64 data since it will be automatically decoded.

**Comment by amimart** [comment]
I'd tend to prefer the `consult/1` reimplementation to manage the base64 decode systematically. This would help keeping the URI logic simple, with not too much responsibility, and above all avoid introducing a breaking change.

**Comment by bdeneux** [comment]
Based on discussion on [PR's review](https://github.com/okp4/okp4d/pull/387#issuecomment-1602454217), we decide to add an option on URI.

The result query reference is now : 

```
cosmwasm:{contract_name}:{contract_address}?query={contract_query}[&base64Decode=true|false].
```
