### ISSUE TITLE
🧠 Logic: `json_prolog` array serialization issue

### ISSUE THREAD

**Issue by amimart** [okp4/okp4d#398]
## Issue description

When unifying a json array through a Prolog empty list to its string representation, it outputs to the string `"[]"` instead of an empty json array: `[]`.

## How to reproduce

This can easily reproduced with a `Ask` query using the CLI:

```sh
> okp4d query logic ask "json_prolog(X, [])." -ojson | jq -r '.answer.results[-1].substitutions[-1].term.name'
'"[]"'
```

We can observe the same results specifying the `'[]'` atom instead of an empty list:

```sh
> okp4d query logic ask "json_prolog(X, [])." -ojson | jq -r '.answer.results[-1].substitutions[-1].term.name'
'"[]"'
```

The reason under this behavior is related to the equality between an empty list and the `'[]'` atom at the interpreter level:

```sh
> okp4d query logic ask "[] = '[]'." -ojson | jq -r '.answer.success'
true
```

## First Analysis

An issue has been opened on the interpreter: https://github.com/ichiban/prolog/issues/296.

It seems this behavior is expected, the SWI-PROLOG implementation having its specific empty list type being not standard.

Should the Prolog interpreter in the logic module be aligned on the standard or the SWI-PROLOG implementation? And then, how do we address the JSON array marshaling?

**Comment by amimart** [comment]
@bdeneux @ccamel I propose to respect to Prolog standard and not head towards SWI-PROLOG _"unconventional"_ empty list consideration.

We still need a solution though, amending the [original specification](https://github.com/okp4/okp4d/issues/348).

A `json(Attributes)` predicate was introduced to manage JSON objects (e.g. `{"b": "a", "a":"c"}` => `json([a-c,b-a])`), may I suggest a similar predicate to handle JSON arrays, like `json_array(Elements)`? It would be consistent with the way we manage objects. Moreover, the original issue is only related to empty arrays so we can support both.

As an example, the following Prolog:

```
json([
    empty-json_array([]),
    filled-[with, something],
    alsoFilled(json_array([0, 1]))
])
```

What are your thoughts?

Would represents:

```json
{
    "empty": [],
    "filled": [
        "with",
        "something"
    ],
    "alsoFilled": [
        0,
        1
    ]
}
```

**Comment by bdeneux** [comment]
@amimart Ok that seems a good solution we could use to allow empty list in json. Maybe to make more consistency we should rename the `json(Attributes)` predicate to `json_obj(Attributes)` or `json_object(Attributes)`. 

We have another solution, is to create a specific atom to represent an empty list, like null (`@(null)`) or boolean value (`@(true)`), we could create the atom `@([])`. But this one is not common so I don't know what is the best solution...

**Comment by ccamel** [comment]
I have a deep feeling, whose origin eludes me, that the choice of using the functor `@` with `[]` as argumentwould be the most appropriate for designating the special value that is the empty list.

**Comment by amimart** [comment]
> I have a deep feeling, whose origin eludes me, that the choice of using the functor `@` with `[]` as argument would be the most appropriate for designating the special value that is the empty list.

@ccamel Yeah it seems simple, just add an `@` in the case of an empty array, I'm ok with that :)
